### PR TITLE
feature: set user and group id because of NFS Share

### PR DESCRIPTION
**Pull request by zlanyi**
…e logging

### CODE REVIEW

**Comment by zlanyi** [comment]
> An error occurred while installing json_pure (2.0.2), and Bundler cannot
continue.
Make sure that `gem install json_pure -v '2.0.2'` succeeds before bundling.

**Comment by zlanyi** [comment]
Hi Guys,

please have a look to Build Job number 708.1 and 708.2. 

There is bundle install error:

> The command "eval bundle install --without system_tests development --path=${BUNDLE_PATH:-vendor/bundle}" failed 3 times.

Details:

> An error occurred while installing json_pure (2.0.2), and Bundler cannot
continue.


All other Build Jobs are successfully done.

Thanks.

Cheers,
Zoltan

**Comment by bastelfreak** [comment]
Hi @zlanyi, please rebase after #255 is merged. That PR provides a fix.

**Comment by zlanyi** [comment]
Hi @bastelfreak ,

done.

Cheers

**Comment by igalic** [comment]
thank you @zlanyi!

**Pull request merged**
