### PR TITLE
Enable installation/configuration of Rundeck v2.8.x.

### LINKED ISSUE #315: Add support for Rundeck v2.7.x
Nike!

### PR DESCRIPTION
**Pull request by dandunckelman**
# Summary
Fixes #315, #300 
Relates to #284

This stems from https://github.com/rundeck/rundeck/issues/2346 (thanks to @gschueler for pointing me in the right direction)

Per the [Rundeck upgrade guide](http://rundeck.org/docs/upgrading/index.html):
- The `/etc/rundeck/profile` has changed.
  - Because the init scripts load an "overrides" file, I decided to have this module simply manage that file, instead of rewriting the file provided by the package maintainer.
- They also changed the namespace for the `PropertyFileLoginModule`

# Questions
- Should I update my spec for when the user sets the `rdeck_profile_template` param?
  - At the bare minimum, I was thinking I'd update the test profile to have "real" content

# Notes
- I've found an issue on v2.7.3 where the `/var/lib/rundeck/.ssh` directory isn't created when the package is installed.  Trying to figure out if that's the responsibility of the package or this module
  - From https://github.com/rundeck/rundeck/issues/2346#issuecomment-286823505:

    > @dandunckelman the rpm spec does create it, but it looks like the .deb postinst script does not. It is just a convention to generate and use a default ssh key, it is really up to the admin how rundeck is to be configured and used
  - So, it seems we'll have to create that directory when `$::rundeck::sshkey_manage` is true (see [here](https://github.com/dandunckelman/puppet-rundeck/blob/fix_profile_for_v2.7.x/manifests/install.pp#L121))
- I've never used the kerberos config, so I assume my changes are satisfactory for that use-case
- This **IS NOT** backwards compatible w/ v2.6.x, and I'm not sure there's a way to make it compatible.  For example:
  - When the values `present`, `installed, or `latest` are specified for `package_ensure`, we have no idea what version will be installed at that time.
  - I think we can only account for it when the version number is explicitly set
- Until https://github.com/rundeck/rundeck/pull/2368 is approved, merged and built into a new Rundeck version **(NOTE:  it was built into the [v2.8.0](http://rundeck.org/docs/history/version-2.8.0.html) release)**, you'll need to do this to get it working:
  - Get a copy of the [Rundeck profile from my PR](https://github.com/dandunckelman/rundeck/blob/8c5f5de23c32d0ed02697c01426aab1a96a09ba9/packaging/debroot/etc/rundeck/profile)
  - Place it in your Puppet module's `templates/` directory
  - Update your class definition of Rundeck to specify the `rdeck_profile_template`.  For example:

        class { '::rundeck':
          rdeck_profile_template => 'MY_MODULE/TEMPLATE',
        }
- I think a future PR should include management of the `rundeck-cli` package
- I'd like to squash commits after some discussion and any new commits
- I've confirmed that this works all the way through to v2.8.2 (latest, ATM)

### CODE REVIEW

**Comment by dandunckelman** [comment]
I'm unsure who to ping around here to try getting some attention on this.

Maybe someone from the "Top contributors" can help?

Ping @liamjbennett @smithtrevor

**Comment by dandunckelman** [comment]
My PR at https://github.com/rundeck/rundeck/pull/2368 was merged.  Hopefully it will go into the next release.

**Comment by af6140** [comment]
This is what i need.

**Comment by dandunckelman** [comment]
@af6140 did you happen to try using it?

**Comment by af6140** [comment]
@dandunckelman Yes, I did, worked fine except the rundeck-config.goovy and rundeck-config.properties issue.

**Comment by bovy89** [comment]
+1

**Comment by jadestorm** [comment]
Thank you for this!  It's working great!  After using the upstream module I did need to basically reinstall rundeck-config because the profile had already been overwritten with missing settings, but once I did this your patch is working great.  +1 for merging this.  (PS I'm running rundeck 2.8.2 so also confirming that it works with that as well)

**Comment by petems** [comment]
@dandunckelman Awesome PR thanks! 

It's possible to wrap this in logic that only applies it if the rundeck version is > 2.7, that would stop the errors for people who are using older rundeck versions. I'll see if I can add some of that logic in a seperate PR and that should be easy to utilise in this PR to make this backwards compatible! 😄

**Comment by dandunckelman** [comment]
@jadestorm glad it works for you.  I just confirmed it works on 2.8.2 as well (I'll update the issue to note that).

@petems Sounds awesome!

**Comment by af6140** [comment]
@dandunckelman ran on 2.8.2 and it works.

**Comment by benh57** [comment]
Could this be merged in?

**Comment by bastelfreak** [comment]
Hi @benh57, thanks for this great PR! Sorry that it took so long for us to respond. Is it still the case, that this only works with Rundeck 2.8.X and not any older releases? If so, please mention it in the README.md

**Comment by bastelfreak** [comment]
We probably need to rebase this PR after https://github.com/voxpupuli/puppet-rundeck/pull/314 got merged

**Comment by bastelfreak** [comment]
oh stupid me.....

@benh57 sorry for the wrong highlight
---

@dandunckelman can you please rebase and update the README.md? Then we should be ready to merge and release.

**Comment by dandunckelman** [comment]
@bastelfreak working on it.

I somehow screwed up the rebase/merge and lost changes.  Fortunately, I had another copy of the module, so I'm slowly finding the missing changes and will add them in another commit that should pass all tests.

**Comment by dandunckelman** [comment]
@bastelfreak should be good to go now

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
