### PR TITLE
Bugfix - fact rundeck_version

### PR DESCRIPTION
**Pull request by fe80**
#### Pull Request (PR) description
Fix facter rundeck_version with new version:
```facter -p rundeck_version 
2018-08-11 10:36:30.168048 ERROR puppetlabs.facter - error while resolving custom fact "rundeck_version": undefined method `[]' for nil:NilClass

rd-acl --version
usage: rd-acl <command> [options...]: test [options]
              Test action:
              rd-acl test [options] : Test existing aclpolicy files
              rd-acl test --dir <path> [options] : Test all aclpolicy files in specific dir
              rd-acl test --file <file> [options] : Test specific aclpolicy file
              rd-acl test -v [options] : Verbose output, including policy definitions to
              resolve failing tests
              Create action:
              rd-acl create [options] : Generate aclpolicy definition based on input options
              rd-acl create -i <audit.log> : Generate aclpolicy definitions to resolve
              rejected access requests
              rd-acl create -i - : Read audit log entries from stdin
options:
 -A,--adhoc                             Adhoc execution (project context)
 -D,--deny <action,...>                 Actions to test are denied (test
                                        command) or to deny (create command).
 -G,--generic <kind>                    Generic resource kind.
 -I,--jobUuid <uuid>                    Job uuid. (project context)
 -P,--projectacl <projectacl>           Project name for ACL policy access, used
                                        in application context.
 -R,--resource <type>                   Resource type name.
 -V,--validate                          Validate all input files.
 -a,--allow <action,...>                Actions to test are allowed (test
                                        command) or to allow (create command).
 -b,--attributes <key=value ...>        Attributes for the resource. A sequence
                                        of key=value pairs, multiple pairs can follow with a space. Use a value of '?'
                                        to see suggestions.
 -c,--context <application | project>   Context: either 'project' or
                                        'application'.
 -d,--dir <dir>                         Directory. Load all policy files in the
                                        specified directory.
 -f,--file <file>                       File path. Load the specified aclpolicy
                                        file.
 -g,--groups <group,...>                Subject Groups names to validate (test
                                        command) or for by: clause (create command).
 -h,--help                              Print this help message
 -i,--input <file | ->                  Read file or stdin for audit log data.
                                        (create command)
 -j,--job <group/name>                  Job group/name. (project context)
 -l,--list                              List all permissions for the group or
                                        user. (test command).
 -n,--node <nodename>                   Node name. (project context)
 -p,--project <project>                 Name of project, used in project context
                                        or for application resource.
 -r,--regex                             Match the resource using regular
                                        expressions. (create command).
 -s,--storage <path/file>               Storage path/name. (application context)
 -t,--tags <tag,..>                     Node tags. If specified, the resource
                                        match will be defined using 'contains'. (project context)
 -u,--user <user,...>                   Subject User names to validate (test
                                        command) or for by: clause (create command).
 -v,--verbose                           Verbose output.
[RUNDECK version 3.0.1-20180803 (0)]
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --version
```

Version add -20180803

#### This Pull Request (PR) fixes the following issues
n/a

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hey @fe80, thanks for the patch. can you please take a look at the used email address in the commit? It isn't associated with your github account.  Please also rebase after https://github.com/voxpupuli/puppet-rundeck/pull/393 got merged. One of our dependencies is broken and needs to be updated. Can you also add a test for your change. it would be helpful if you can mock the input to the fact with the real output of `rd-acl -h`. Let us know if you have any questions.

**Comment by fe80** [comment]
Hi @bastelfreak ! Yes sorry for the github account I've push with my office account, it's fixed. I waiting your merge.

**Comment by bastelfreak** [comment]
@fe80 I cherry-picked your commit into my PR #393. Would you mind taking a look at the travis error?

**Comment by bastelfreak** [comment]
@fe80 can you please rebase and add a test for the change?

**Comment by bastelfreak** [comment]
I'm going to close this. It got implemented in https://github.com/voxpupuli/puppet-rundeck/pull/402

**Pull request closed without merging**
