### PR TITLE
Add code for secrets management in keystorage

### PR DESCRIPTION
**Pull request by Joris29**
#### Pull Request (PR) description
This adds a config define to add secrets to Rundeck key storage.

### CODE REVIEW

**Comment by Joris29** [comment]
@bastelfreak If you have time could you take a look also a question regarding access rights could I get access to close old issues?

**Review by witjoh — APPROVED** [review]

**Comment by nosrio** [comment]
+1

**Comment by kpolucas** [comment]
+1 to this

**Comment by Joris29** [comment]
@kenyon ?

**Review by kenyon — APPROVED** [review]

**Pull request merged**
