### PR TITLE
Add scm config options to project define

### LINKED ISSUE #541: manage SCM configuration of projects
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
   7.0
- Ruby:
- Distribution:
   Ubuntu
- Module version:
  9.1.0

## How to reproduce (e.g Puppet code you use)
in module versions up to 8.0.1 there is functionality to manage project SCM configuration
how to configure SCM in version 9.1.0

### PR DESCRIPTION
**Pull request by Joris29**
#### Pull Request (PR) description
This PR adds a scm_config parameter which allows to configure SCM for a Rundeck project.

#### This Pull Request (PR) fixes the following issues
Fixes #541

### CODE REVIEW

**Review by witjoh — APPROVED** [review]

**Comment by Joris29** [comment]
@bastelfreak Could you take a look when you have time?

**Comment by nosrio** [comment]
+1

**Comment by kpolucas** [comment]
please  +1 to this

**Review by kenyon — APPROVED** [review]
Needs a rebase to fix the merge conflict in `REFERENCE.md`, but otherwise looks good.

**Review by kenyon — APPROVED** [review]

**Pull request merged**
