### PR TITLE
Added option to template : 'forceBindingLoginUseRootContextForRoles'

### PR DESCRIPTION
**Pull request by zlanyi**
Added option 'forceBindingLoginUseRootContextForRoles' to template.
Change cacheDurationMillis as variable due to test/debug.

### CODE REVIEW

**Comment by zlanyi** [comment]
fixed

**Comment by zlanyi** [comment]
Travis has a problem with ruby install...

**Comment by jyaworski** [comment]
@zlanyi we're trying to get #227 merged to fix this.

**Comment by jyaworski** [comment]
Hi @zlanyi. Can you rebase on the latest master?

**Pull request merged**
