### PR TITLE
modulesync 2.12.0

### PR DESCRIPTION
**Pull request by bastelfreak**
modulesync 2.9.0

### CODE REVIEW

**Comment by dhoppe** [comment]
We might need to use ```fact()``` instead of ```$facts[]```:
* https://travis-ci.org/github/voxpupuli/puppet-rundeck/jobs/685013077#L2856

**Comment by ekohl** [comment]
No, if you change the facts you use, you also need to update the overriding code. Done now and I hope the tests will pass.

**Comment by ekohl** [comment]
Looks like Debian 8 is an issue: https://github.com/voxpupuli/puppet-rundeck/pull/443

**Comment by ekohl** [comment]
:green_heart:

**Comment by ekohl** [comment]
Oh, looks like Travis hasn't started yet.

**Comment by ekohl** [comment]
Looks like I missed one. Pushed an update

**Pull request merged**
