### PR TITLE
puppetlabs/apt: Allow 8.x

### PR DESCRIPTION
**Pull request by bastelfreak**
also contains:
* https://github.com/voxpupuli/puppet-rundeck/pull/464
* https://github.com/voxpupuli/puppet-rundeck/pull/463
* https://github.com/voxpupuli/puppet-rundeck/pull/465
* https://github.com/voxpupuli/puppet-rundeck/pull/466
* https://github.com/voxpupuli/puppet-rundeck/pull/467

### CODE REVIEW

**Comment by bastelfreak** [comment]
this now depends on a new puppetlabs/java release :(

**Comment by dandunckelman** [comment]
Just curious, what's causing all of these PRs to drag?

**Comment by smortex** [comment]
There where 2 patch releases of puppetlabs/puppetlabs-java, including commits which bump version requirements… Maybe it's fine now?

**Comment by smortex** [comment]
```
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: Reading package lists...
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: Failed to fetch dl.bintray.com/rundeck/rundeck-deb/InRelease  403  Forbidden [IP: 34.216.31.34 443]
  Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: E: The repository 'dl.bintray.com/rundeck/rundeck-deb  InRelease' is not signed.
```

Similar failure to download rpms…

@dandunckelman I guess packages where relocated… I tried to click through rundeck.com and ended-up browsing packages here:
https://packages.rundeck.com/pagerduty/rundeck

**Review by smortex — APPROVED** [review]

**Pull request merged**
