### PR TITLE
Simplify the acl template

### PR DESCRIPTION
**Pull request by grafjo**

### CODE REVIEW

**Comment by liamjbennett** [comment]
This is ok with me. Just need to fix the Travis builds - which is think is just some trailing commas.

**Comment by jyaworski** [comment]
Has this been confirmed to produce the same output? It was formatted that way because of some discrepancies in the way it can be specified (say, in hiera) versus the way rundeck accepts it.

**Comment by jyaworski** [comment]
@grafjo it looks good, but it appears to be getting indented by two spaces or so, so the test fails.

**Comment by jyaworski** [comment]
Actually, they're equivalent. I'm going to merge this then submit a PR to fix the tests.

**Comment by grafjo** [comment]
hi @jyaworski, 

sorry that i didn't fixed the tests - i had no luck fixing it =/

**Pull request merged**
