### PR TITLE
enable users to set the framework_config_url

### PR DESCRIPTION
**Pull request by sjsmit**
currently framework_config_url is always overridden to $::fqdn.
this change allows users to set the url and port themselves in the framework_config hash

### CODE REVIEW

**Comment by cjtoolseram** [comment]
#303

**Comment by mibaboo** [comment]
@sjsmit I notice you MR has not been merged yet. Is there a work around?

**Comment by wyardley** [comment]
This may need a rebase (and some adjustments) when #343 is merged.
Not sure but I think a test might be a good idea (to test the various cases), as well as a squash.

**Comment by wyardley** [comment]
Closing via #356, would appreciate if someone can test

**Pull request closed without merging**
