### PR TITLE
Fix ACLs rendering when using atributes as filters

### LINKED ISSUE #391: Incorrect example in comments for acl policy file
plural groups and usernames in example: https://github.com/voxpupuli/puppet-rundeck/blob/5d31e83dfd9b1e59e82a9e95116b0feb88f26739/manifests/config/aclpolicyfile.pp#L58-L59

singular group and username in template: https://github.com/voxpupuli/puppet-rundeck/blob/5d31e83dfd9b1e59e82a9e95116b0feb88f26739/templates/aclpolicy.erb#L25-L37

### LINKED ISSUE #512: ACLs render incorrectly when using attributes filters
When creating an acl to filter using nodes attributes the acl file is rendered incorrectly

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby:
- Distribution:
- Module version: 8

## How to reproduce (e.g Puppet code you use)

Using this ACL
```
rundeck::config::aclpolicyfile { 'read-qa-nodes':
  acl_policies => [
     {
        'description' => 'Read qa nodes',
        'context' => {
          'project' => '.*'
        },
        'for' => {
          'node' => [
            { 'match' => { 'environment' => 'qa' }, 'allow' => ['read'] }
          ]
        },
        'by' => [
          { 'group' => ['qa'] }
        ]
      }
  ]
}
```

## What are you seeing

The ACL rendered is this:

```
description: 'Read qa nodes'
context:
  project: '.*'
for:
  node:
    - match:
      environment: 'qa'    ### <-- THIS IS INCORRECT
      allow: ["read"]
by:
  group:
    - 'qa'
```
## What behaviour did you expect instead

The ACL should be this (with the extra indent)

```
description: 'Read qa nodes'
context:
  project: '.*'
for:
  node:
    - match:
        environment: 'qa'
      allow: ["read"]
by:
  group:
    - 'qa'
```

### PR DESCRIPTION
**Pull request by nosrio**
#### This Pull Request (PR) fixes the following issues

Fixes #391 
Fixes #512

### CODE REVIEW

**Comment by nosrio** [comment]
@bastelfreak Please review this. The same check from #511 are failing, could you help me fix them?

**Comment by bastelfreak** [comment]
mhm I've no idea why it fails :(
I asked on IRC.

**Comment by jay7x** [comment]
I'm not sure if it's ok to blindly remove it.. I guess H2 DB is bundled with Rundeck. If so then it'd be better to recheck which version has H2 DB version >= 1.4.198. Then add/remove `MVCC=true` based on the version. But I'm not a rundeck user so just my 2$c here :)

**Comment by nosrio** [comment]
From [this](https://github.com/rundeck/rundeck/issues/7724) and [this](https://docs.rundeck.com/docs/history/4_x/version-4.1.0.html#overview) I understand that is not really necessary to have the setting `MVCC=true` if using everthing as default.

**Review by jay7x — APPROVED** [review]

**Pull request merged**
