### PR TITLE
Modulesync 4.0.0

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
CentOS 6 fails. Given it's going EOL soon I'm inclined to drop it.

**Comment by ekohl** [comment]
Careful that this now includes a drop EL6 support commit which is backwards incompatible.

**Comment by bastelfreak** [comment]
I created https://github.com/voxpupuli/puppet-rundeck/issues/456. that will update the next changelog with a note that centos 6 was dropped.

**Comment by ekohl** [comment]
For some reason the Puppet 6 tests timed out, restarted them. Otherwise I think this should be ready to merge.

**Review by bastelfreak — APPROVED** [review]

**Comment by ekohl** [comment]
Something odd is happening with the Puppet 6 tests. They're running for ages.

**Comment by ekohl** [comment]
Locally I can also see that the fact unit tests create an infinite loop. No idea why and if this is Facter 4 related.

**Comment by alexjfisher** [comment]
> Locally I can also see that the fact unit tests create an infinite loop. No idea why and if this is Facter 4 related.

Should we be testing puppet 6 with facter 4?

**Comment by alexjfisher** [comment]
Same result with facter 2.5.7 (just slower looping!)

**Comment by alexjfisher** [comment]
Also looping for me locally with Puppet 5...

**Comment by ekohl** [comment]
I can't really explain it. At first I thought that the loading in https://github.com/voxpupuli/puppet-rundeck/blob/master/lib/facter/rundeck_version.rb might throw it off (given it's doing conditional things).

What's even more fascinating is that if I replace the content with:
```ruby
require 'spec_helper'
  
describe 'facts' do
  context 'bla' do
    it { expect(true).to eq(true) }
  end
end
```

It actually outputs this:
```
facts
  bla
    is expected to eq true

facts
  bla
    is expected to eq true
```

Somehow that is already executed twice.

**Comment by ekohl** [comment]
Moving it to a different location helped ...

**Comment by ekohl** [comment]
FYI: I think this is good to go but since I opened the PR I can't approve it.

**Review by bastelfreak — APPROVED** [review]

**Pull request merged**
