### PR TITLE
Order variables alphabetically

### PR DESCRIPTION
**Pull request by danifr**
https://github.com/voxpupuli/puppet-rundeck/issues/188

Some things to take into account:
* I didn't change params.pp. Not sure if sorting makes sense here
* I didn't sort any of the documented sections

What do you guys think?

### CODE REVIEW

**Comment by jyaworski** [comment]
Ordering of the docs doesn't _really_ matter. It would be nice if they were in the same order, though. It would make adding new docs easier.

**Comment by danifr** [comment]
>> Ordering of the docs doesn't really matter. It would be nice if they were in the same order, though. It would make adding new docs easier.

Any ideas on how to automate it? Doing it by hand seems like an endless task and incredibly error prone.

**Comment by danifr** [comment]
I **_kinda_** found a way to automate it. (thanks to http://stackoverflow.com/questions/6924816/sort-2-line-blocks-of-a-file)

This is how I did it:

1. ` %s/*]\n/*]/g`
2. `sort` 
3. `%s/*]/*]\r/g`
4. `%s/# \[\*/#\r# \[\*/g`

**Comment by jyaworski** [comment]
Is this still WIP? Can you squash?

**Comment by danifr** [comment]
Yep, I think is ready to be merged. Thanks.

**Pull request merged**
